<?php
/**
 * File Name: GenerateControllerFile.php
 * ©2020 All right reserved Qiaotongtianxia Network Technology Co., Ltd.
 * @author: hyunsu
 * @date: 2021/4/6 11:23 上午
 * @email: hyunsu@foxmail.com
 * @description:
 * @version: 1.0.0
 * ============================= 版本修正历史记录 ==========================
 * 版 本:          修改时间:          修改人:
 * 修改内容:
 *      //
 */

namespace qh4module\qhgc\models\server;


use qh4module\qhgc\models\GenerateTool;
use QTTX;
use qttx\helper\StringHelper;

class GenerateControllerFile
{
    public $dir;
    public $controller_name;
    public $namespace;
    public $model_namespace;
    public $active_record_classname;
    public $model_classname;
    public $fun_index;
    public $fun_create;
    public $fun_update;
    public $fun_detail;
    public $fun_delete;


    public function run()
    {
        // 获取类名
        $class_name = $this->getClassName();

        $ar_content = GenerateTool::loadTemplate($this->template(), [
            'classname' => $class_name,
            'time' => date('Y-m-d H:i:s'),
            'namespace' => $this->namespace,
            'version' => VERSION,
            'model_namespace'=>$this->model_namespace,
            'active_record_classname'=>$this->active_record_classname,
            'model_classname'=>$this->model_classname,
            'action_index'=>$this->getActionName($this->fun_index),
            'action_create'=>$this->getActionName($this->fun_create),
            'action_update'=>$this->getActionName($this->fun_update),
            'action_detail'=>$this->getActionName($this->fun_detail),
            'action_delete'=>$this->getActionName($this->fun_delete),
        ]);

        $filename = StringHelper::combPath($this->dir, $class_name . '.php');
        file_put_contents($filename, $ar_content);
    }

    private function getActionName($action)
    {
        $act = '';
        if (empty(QTTX::$request->actionBeforeFix)) {
            $act = $action;
        } else {
            $act = QTTX::$request->actionBeforeFix . ucfirst($action);
        }
        $act .= QTTX::$request->actionAfterFix;
        return $act;
    }

    public function getClassName()
    {
        return QTTX::$request->ctrlBeforeFix
        . ucfirst($this->controller_name)
        . QTTX::$request->ctrlAfterFix;
    }

    protected function template()
    {
        return '<?php
/**
 * File Name: {{classname}}.php
 * Automatically generated by QHGC tool
 * @date: {{time}}
 * @version: {{version}}
 */

namespace {{namespace}};


use qttx\web\Controller;
use {{model_namespace}}\Index;
use {{model_namespace}}\Create;
use {{model_namespace}}\Update;
use {{model_namespace}}\Delete;
use {{model_namespace}}\Detail;

/**
 * Class {{classname}}
 * @package {{namespace}}
 * 使用 \{{active_record_classname}} 对 \{{model_classname}} 进行增删改查操作
 * @see \{{active_record_classname}}
 * @see \{{model_classname}}
 */
class {{classname}} extends Controller
{
    /**
     * 分页获取数据
     * @return array [total,list,page,limit]
     */
    public function {{action_index}}()
    {
        $model = new Index();

        return $this->runModel($model);
    }

    /**
     * 新增一条数据
     */
    public function {{action_create}}()
    {
        $model = new Create();

        return $this->runModel($model);
    }

    /**
     * 更新单条数据
     */
    public function {{action_update}}()
    {
        $model = new Update();

        return $this->runModel($model);
    }

    /**
     * 删除多条数据
     */
    public function {{action_delete}}()
    {
        $model = new Delete();

        return $this->runModel($model);
    }

    /**
     * 获取一条记录的详细信息
     * @return array
     */
    public function {{action_detail}}()
    {
        $model = new Detail();

        return $this->runModel($model);
    }
}';
    }
}