<?php
/**
 * File Name: GenerateModuleFile.php
 * ©2020 All right reserved Qiaotongtianxia Network Technology Co., Ltd.
 * @author: hyunsu
 * @date: 2021/4/9 11:16 上午
 * @email: hyunsu@foxmail.com
 * @description:
 * @version: 1.0.0
 * ============================= 版本修正历史记录 ==========================
 * 版 本:          修改时间:          修改人:
 * 修改内容:
 *      //
 */

namespace qh4module\qhgc\models\server;


use qh4module\qhgc\models\GenerateTool;
use qttx\helper\StringHelper;

class GenerateModuleFile
{
    public $dir;
    public $namespace;
    public $classname = 'Module';

    public function run()
    {
        $content = GenerateTool::loadTemplate($this->template(), [
            'classname' => $this->classname,
            'time' => date('Y-m-d H:i:s'),
            'namespace' => $this->namespace,
            'version' => VERSION,
        ]);


        $filename = StringHelper::combPath($this->dir, $this->classname . '.php');
        file_put_contents($filename, $content);
    }

    protected function template()
    {
        return '<?php
/**
 * File Name: {{classname}}.php
 * Automatically generated by QHGC tool
 * @date: {{time}}
 * @version: {{version}}
 */

namespace {{namespace}};


class {{classname}} extends \qttx\web\Module
{

}';
    }
}