<?php
/**
 * File Name: GenerateDetailModelFile.php
 * ©2020 All right reserved Qiaotongtianxia Network Technology Co., Ltd.
 * @author: hyunsu
 * @date: 2021/4/7 2:42 下午
 * @email: hyunsu@foxmail.com
 * @description:
 * @version: 1.0.0
 * ============================= 版本修正历史记录 ==========================
 * 版 本:          修改时间:          修改人:
 * 修改内容:
 *      //
 */

namespace qh4module\qhgc\models\server;


use qh4module\qhgc\external\ExtQhgc;
use qh4module\qhgc\models\GenerateTool;
use qttx\helper\StringHelper;

class GenerateDetailModelFile
{
    public $dir;
    public $columns;
    public $classname = 'Detail';
    public $namespace;
    public $active_record_classname;
    public $model_classname;
    public $table_name;
    /**
     * @var ExtQhgc
     */
    public $external;

    protected $use_class;

    public function run()
    {
        $alias = call_user_func([$this->active_record_classname, 'tableAlias']);

        $primary = call_user_func([$this->active_record_classname, 'primaryKey']);

        $this->use_class[] = $this->active_record_classname;
        $this->use_class[] = $this->model_classname;

        $content = GenerateTool::loadTemplate($this->template(), [
            'classname' => $this->classname,
            'time' => date('Y-m-d H:i:s'),
            'namespace' => $this->namespace,
            'version' => VERSION,
            'active_record_classname' => GenerateTool::fullClass2Single($this->active_record_classname),
            'model_classname' => GenerateTool::fullClass2Single($this->model_classname),
            'table_name' => $this->table_name,
            'primary' => $primary,
            'all_field' => GenerateIndexModelFile::getAllField($this->columns, $alias,false),
            'use_class' => GenerateTool::formatUseClass($this->use_class),
        ]);


        $filename = StringHelper::combPath($this->dir, $this->classname . '.php');
        file_put_contents($filename, $content);
    }

    protected function template()
    {
        return '<?php
/**
 * File Name: {{classname}}.php
 * Automatically generated by QGC tool
 * @date: {{time}}
 * @version: {{version}}
 */

namespace {{namespace}};


{{use_class}}

/**
 * Class {{classname}}
 * 获取{{table_name}}表的单条数据详细信息
 * @package {{namespace}}
 */
class {{classname}} extends {{model_classname}}
{
    /**
     * @var string|int 接收参数,必须：主键
     */
    public ${{primary}};
    
    /**
     * @inheritDoc
     */
    public function rules()
    {
        return [
            [[\'{{primary}}\'],\'required\'],
        ];
    }

    /**
     * @inheritDoc
     */
    public function run()
    {
        // 所有的字段,根据需要删减
        $fields = [{{all_field}}];
        $result = {{active_record_classname}}::findOne($this->{{primary}},$fields);
        if (empty($result)) {
            $this->addError(\'{{primary}}\', \'查询条目不存在\');
            return false;
        }
        return $result->toArray();
    }
}
';
    }
}